# Generated by Django 5.0.14 on 2026-06-16 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_must_change_password_registrationrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='allowed_nav_paths',
            field=models.JSONField(blank=True, help_text='Rental staff: nav paths the owner granted. Copied to the User on approval.', null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Rental owner who created this staff request (rental_staff role only).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_staff_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='rental_parent',
            field=models.ForeignKey(blank=True, help_text='For rental staff: the rental owner they belong to. Null for everyone else.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('rental', 'Rental'), ('mechanic', 'Mechanic'), ('rental_staff', 'Rental staff')], db_index=True, max_length=20),
        ),
    ]
