# Generated by Django 5.0.14 on 2026-06-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
