# Generated by Django 5.0.14 on 2026-06-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_migrate_inactive_to_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
