# Generated by Django 5.0.14 on 2026-06-16 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('rego', models.CharField(blank=True, max_length=20)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20)),
                ('total_distance_km', models.PositiveIntegerField(default=0)),
                ('trips', models.PositiveIntegerField(default=0)),
                ('oil_due_date', models.DateField(blank=True, null=True)),
                ('rego_due_date', models.DateField(blank=True, null=True)),
                ('rent_price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('minimum_rental_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(help_text='The rental owner that owns this vehicle.', limit_choices_to={'role': 'rental'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
