# Generated by Django 5.0.14 on 2026-06-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('ctp', 'Compulsory Third Party'), ('third_party_property', 'Third-Party Property Damage'), ('third_party_fire_theft', 'Third-Party Fire and Theft'), ('comprehensive', 'Comprehensive Car Insurance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
