# Generated by Django 5.0.14 on 2026-06-18 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_vehicle_image_urls_vehicle_insurance_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField(help_text='The work the rental needs done.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_unit', models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days')], max_length=10)),
                ('mechanic_notes', models.TextField(blank=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic', models.ForeignKey(blank=True, limit_choices_to={'role': 'mechanic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_as_mechanic', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests_as_rental', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='operations.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
