# Generated by Django 5.0.14 on 2026-06-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
