# Generated by Django 5.0.14 on 2026-06-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_maintenancerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='maintenance_note',
            field=models.TextField(blank=True),
        ),
    ]
