# Generated by Django 5.0.14 on 2026-06-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_vehicle_maintenance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_oil_change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_rego_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
