# Generated by Django 5.0.14 on 2026-06-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_vehicle_last_oil_change_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='id_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='info_request_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='verified_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='id_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='info_request_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='verified_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('info_requested', 'Information requested')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('info_requested', 'Information requested')], db_index=True, default='pending', max_length=20),
        ),
    ]
