# Generated by Django 5.0.14 on 2026-06-22 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_maintenancerequest_id_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(choices=[('oil', 'Oil change'), ('rego', 'Rego expiry')], max_length=10)),
                ('due_date', models.DateField()),
                ('sent_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_reminder_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='operations.vehicle')),
            ],
            options={
                'unique_together': {('recipient', 'vehicle', 'ntype', 'sent_date')},
            },
        ),
    ]
