# Generated by Django 5.0.14 on 2026-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_vehiclereminderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('info_requested', 'Information requested'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('pending_return', 'Pending return'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclereminderlog',
            name='ntype',
            field=models.CharField(choices=[('oil', 'Oil change'), ('rego', 'Rego expiry'), ('return', 'Return due')], max_length=10),
        ),
    ]
