# Generated by Django 5.0.14 on 2026-06-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_alter_rentalrequest_status_alter_vehicle_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='work_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('pending_return', 'Pending return'), ('completed', 'Completed'), ('info_requested', 'Information requested')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclereminderlog',
            name='ntype',
            field=models.CharField(choices=[('oil', 'Oil change'), ('rego', 'Rego expiry'), ('return', 'Return due'), ('maint', 'Maintenance overdue')], max_length=10),
        ),
    ]
