# Generated by Django 5.0.14 on 2026-06-23 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_maintenancerequest_work_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('by_staff', models.BooleanField(default=False)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('summary', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_performed', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(help_text='The rental owner this activity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
