# Generated by Django 5.0.14 on 2026-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_locationwarning_vehiclelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
