# Generated by Django 5.0.14 on 2026-06-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_rentalrequest_running_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='return_state',
            field=models.CharField(blank=True, choices=[('', 'None'), ('requested_by_rental', 'Early return requested by rental'), ('requested_by_driver', 'Early return requested by driver'), ('period_ended', 'Rental period ended'), ('driver_completed', 'Driver completed trip')], default='', max_length=20),
        ),
    ]
