# Generated by Django 5.0.14 on 2026-06-30 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_rentalrequest_return_requested_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(db_index=True, max_length=40)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('cascade_counts', models.JSONField(blank=True, default=dict)),
                ('cascade_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
