# Generated by Django 5.0.14 on 2026-06-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_deletionaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#f59e0b', max_length=7)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site branding',
                'verbose_name_plural': 'Site branding',
            },
        ),
    ]
