# Generated by Django 5.0.14 on 2026-06-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_sitebranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('running', 'Running'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('pending_return', 'Pending return'), ('completed', 'Completed'), ('info_requested', 'Information requested')], db_index=True, default='pending', max_length=20),
        ),
    ]
